[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

[".SpaceVim"]
    type = "git-repo"
    url = "https://gitlab.com/SpaceVim/SpaceVim.git"
    refreshPeriod = "168h"

[".config/textmate/tiltfile.tmbundle"]
    type = "git-repo"
    url = "https://github.com/tilt-dev/tiltfile.tmbundle.git"
    refreshPeriod = "168h"

[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "168h"


#[".task/hooks/on-add.task2habitica"]
#type = "file"
#url = "https://raw.githubusercontent.com/robwhitaker/taskwarrior-habitica-bridge/master/hooks/on-add.task2habitica"
#refreshPeriod = "168h"
#executable = true
#
#[".task/hooks/on-exit.task2habitica"]
#type = "file"
#url = "https://raw.githubusercontent.com/robwhitaker/taskwarrior-habitica-bridge/master/hooks/on-exit.task2habitica"
#refreshPeriod = "168h"
#executable = true
#
#[".task/hooks/on-modify.task2habitica"]
#type = "file"
#url = "https://raw.githubusercontent.com/robwhitaker/taskwarrior-habitica-bridge/master/hooks/on-modify.task2habitica"
#refreshPeriod = "168h"
#executable = true
