[".oh-my-zsh"]
    type = "git-repo"
    url = "git@github.com:ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

[".SpaceVim"]
    type = "git-repo"
    url = "git@github.com:SpaceVim/SpaceVim.git"
    refreshPeriod = "168h"
