[".oh-my-zsh"]
    type = "git-repo"
    url = "git@github.com:ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

[".SpaceVim"]
    type = "git-repo"
    url = "git@github.com:SpaceVim/SpaceVim.git"
    refreshPeriod = "168h"

[".config/textmate/tiltfile.tmbundle"]
    type = "git-repo"
    url = "git@github.com:tilt-dev/tiltfile.tmbundle"
    refreshPeriod = "168h"

[".***REMOVED***"]
    type = "git-repo"
    url = "https://github.com/***REMOVED***-vm/***REMOVED***.git"
    refreshPeriod = "168h"
