repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  -   repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.10.0
      hooks:
      -   id: shellcheck
