#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
#guifont = "Fira Code Mono:h12"
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = "defx"
#   bootstrap_after="cargo_task"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
 name = "lang#java"

[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx2G",
    "-jar",
    "~/Anwendungen/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar",
    "-configuration",
    "~/.config/dt-language-server-latest/config_linux",
    "-data",
    "~/.cache/javalsp"
    ]

[[layers]]
  name = "lang#c"

[[layers]]
  name = 'lang#clojure'

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#rust"
[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
    ]
  [layers.override_cmd]
      rust = ["rls"]
[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

