#!/bin/bash

### BEGIN INIT INFO
# Provides:          payaradomain
# Required-Start:    $local_fs $syslog $time $network
# Required-Stop:     $local_fs $syslog $time &network
# Should-Stop:       postgresql
# Should-Start:      postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the PayaraDomain
# Description:       Same as Short
#
### END INIT INFO

# Author: Manuel Müller,Oracle


# NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2011 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

# Linux Platform Services for GlassFish
# See this blog for more details:
# http://blogs.sun.com/foo/entry/run_glassfish_v3_as_a
# Remove the GF_USER setting to have the System account run GlassFish
#
#    Created on : Fri Apr 03 15:03:07 CEST 2015
#     Server Type:  Domain

#ASADMIN="/opt/payara41/glassfish/lib/nadmin"
ASADMIN="/opt/payara41/bin/asadmin"
DOMAINDIR="/opt/payara41/glassfish/domains"


case "$1" in
start)
    $ASADMIN start-domain    --domaindir $DOMAINDIR payaradomain && curl http://localhost:8080/firemessage/login.xhtml && curl --data "user=test.müller&token=***REMOVED***&debug=true&message=start_Bot" http://localhost:8080/firemessage/api/alarm/post &
    ;;
stop)
    $ASADMIN stop-domain   --domaindir $DOMAINDIR payaradomain &
    ;;
restart)
    $ASADMIN restart-domain   --domaindir /opt/payara41/glassfish/domains  payaradomain &
    ;;
*)
    echo "usage: $0 (start|stop|restart|help)"
esac

#
# Example commands that demonstrate how to run GlassFish on the "special" ports < 1024
#
#iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
#iptables -t nat -A PREROUTING -p udp -m udp --dport 80 -j REDIRECT --to-ports 8080
