#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-scale $SCRIPTPATH/down.jpg
#fi

leftwm-command "UnloadTheme"

redshift -x
pkill compton
pkill picom
pkill nm-applet
pkill das-keyboard-w
pkill volumeicon
pkill polybar
pkill redshift-gtk
pkill wired
