autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nopager: false
notifications: true
parsing: true
path: /home/triantium/.local/share/gopass/stores/root
safecontent: false
mounts:
    geek: /home/triantium/.local/share/gopass/stores/geek
    personal: /home/triantium/.local/share/gopass/stores/personal
