[kubernetes]
disabled = false

[[battery.display]]
threshold = 17
style = "bold red"

[custom.git-town]
command = "git town status --pending"
format = "[ $output ]($style)"
style = "bg:yellow fg:black"
when = "test -n \"$(git town status --pending)\" "
